### ISSUE TITLE
Cocoapods installation with 'use_frameworks!' does fail with 'Could not build Objective-C module 'pomo_iphone'

### ISSUE THREAD

**Issue by bestimmaa** [pronebird/pomo-iphone#1]
The installation does fail for podfiles with the `use_frameworks!`enabled when integrating into a Swift project. The `import pomo_iphone
` fails with `Could not build Objective-C module 'pomo_iphone`.  It seems like there is no framework but only a static lib provided. Any workarounds for this? I want to use it in a Swift project that needs to have `use_frameworks!` enabled.

**Comment by pronebird** [comment]
Hi @bestimmaa, I'll take a look later today. I suspect pod spec file is out of date.

**Comment by bestimmaa** [comment]
Thank you very much for your quick response!

**Comment by pronebird** [comment]
I put some efforts to solve this in `develop` branch and stumble upon the fact that `_` is actually a reserved key in swift and I use it as helper function to obtain single translation. Still have to make sure all nullability annotations are in place and correct.

**Comment by pronebird** [comment]
Cool so in Swift `_(singular)` becomes `__(singular)` which looks pretty cool. Check out develop branch and see how it works. It's far from perfect but nevertheless.

**Comment by bestimmaa** [comment]
Thank you for this! Also stumbled across the _ problem. Now we need official support for the Swift language in xgettext 👍
