### ISSUE TITLE
muparser not getting installed

### ISSUE THREAD

**Issue by raviAggarwal61** [pronebird/pomo-iphone#2]
@pronebird 
Hi, 
I tried installing pod using **pod 'pomo-iphone', :git => 'git://github.com/pronebird/pomo-iphone.git'** and only pomo-iphone got installed but not the muparser dependency, which leads to an error saying 
**'muParserInt.h' file not found**

Can you please tell me the correct way to install?
<img width="820" alt="screen shot 2017-04-07 at 11 33 25 am" src="https://cloud.githubusercontent.com/assets/26619190/24787468/11c145d0-1b86-11e7-8cf0-2c0be843ba64.png">

**Comment by pronebird** [comment]
Hi,

Makes sense, I need to find the way to pull submodules  on pod installation. For now to fix that, just run manually from Pod's folder:

> git submodule update --init --recursive

**Comment by pronebird** [comment]
I've updated installation notes, please use `:submodules => true` option to git url, i.e:

`pod 'pomo-iphone', :git => 'git://github.com/pronebird/pomo-iphone.git', :submodules => true`
